= General Terminology
This page lists general terms to be used to describe the concepts or components.

== Translation Terms
[glossary]
Copy Source::
  Copy source strings to translation entries.

Entry::
  A data structure that holding the relation between an source string, plural from, context, flags, comments, and translated texts. (Definition from gettext). In message list view, it represent a row. An entry may contains multiple source strings and translation strings.

Entry Row (Row)::
  A row in the message list that hold an entry. The top row is row 1 and so on. Note that a row may contain multiple source and translation entries if plural is required.

Source String::
  A string to be translated. In terms of gettext, it represents msgid or msgid_plural.

State Filter::
  A set of checkboxes for filtering the translation strings by its state.

Translation State::
  The state of translation. It can be new, fuzzy, translated, rejected or approved.

Translation String::
  A string of translation. In terms of gettext, it represents msgstr or msgstr[n].

Translation Unit Detail::
  Data about an entry. E.g. Message Context, entry Serial number, and REST id.


== Web UI Terms
[glossary]
Autocomplete::
  An action on text field or text box that it predicts the complete word by typing only part of the word.

Breadcrumb::
  An widget for keeping track their locations.

Checkbox::
  A widget for binary choice.

Focus::
  The widget that currently receiving keyboard input.

Hyperlink::
  A UI widget that point to a web page or anchor of a web page.

Menu::
  A collection of options or commands for user to click from.

Web Page::
  A web document that can be identified with URL.

Widget::
  A UI element for viewing or interacting.

