= Web UI Taxonomy
This pages shows a taxonomy on Web UI components (referred as widgets).

== Dialog
Dialog:: A windowed widget that prompt user for an acknowledgement. It closes after acknowledgement received. It should also close when move away from current web page.
  Modal Dialog;; A dialog that block the actions to parent web page until it close.
  Keyboard shortcut dialog;; A dialog that shows the enabled keyboard shortcut.

== List
List:: An ordered group of items of same kind. E.g. Project List, Document List.
  Pager List;; A List that will show more items whenever user clicks "more".
    Activity List::: A Pager List for activities.
    Maintained Project List::: A Pager List for user maintained projects.
  Paged List;; A List that will be split in to different pages if its length reached a given length.
    Document List:::  A Paged List that shows documents.
    Group List::: A Paged List that shows groups.
    Language List:::  A Paged List that shows languages.
      Server Language List;;;  A Paged List that shows server supported languages.
      Project-Version Language List;;;  A Paged List that shows languages enabled in the project-version.
    Project List::: A Paged List for projects.
    Project-Version Language List:::  A Paged List that shows languages enabled in the project-version.
    Version List::: A Paged List that shows versions.
    Glossary List::: A Paged List that shows glossaries.

== Panel
Panel:: A widget that contains other widgets and occupies an area in view. E.g. Setting Panel, Translation Memory Panel.
  Chat Room Panel;; A Panel that shows chat room log and text box for chat message.
  Glossary Panel;;  A Panel that shows the glossary.
  Notification Panel;;  A Panel that displays notification.
  Option Panel;; A Panel that shows configuration options.
  Validation Option Panel;; A Panel that shows validation options.
  Translation Memory (TM) Panel;; A Panel that shows translation memory.

== Progress Indicators
Progress Indicator:: A Widget that showing that some action is currently undertaken.
  Progress Bar;; A Progress Indicator that show the percentage of completion.

== Selection
Radio Button:: A Widget for choosing exactly on of a predefined set of options.

Drop-Down:: A Widget for selecting exactly one option. It expands to show a set of options when clicked; it clasped when user move focus or select an option.

List Box:: A Widget that allows the user to select one or more items from a list contained within a static, multiple line text box.

== Statistics 
Percentage Bar:: A Widget that shows the percentage of given items. Like percentage of words are translated.

Translation Statistics Table:: A Widget that shows the translation statistics in table.

== Text Input
Text Box:: A Widget that allows text editing or displaying.
  Text Editor;; A Text Box that allows multi-lined text editing.
    Highlighting Editor::: The Text Editor that does syntax highlighting.
    Source Editor::: A read-only Text Editor that holds Source String.
    Translation Editor;;; A Text Editor that holds Translation String.
       Translation Entry::: A set of Translation Editors that belongs to an Entry.
  Text Field;;  A Text Box that allows one-lined text editing or displaying.
    Password Field::: A Text Field that masks input string for password input.  
    Search Field::: A Text Field that trigger the search on input term by pressing "enter".
      Project Search Field;;;  A Search Field that searchs projects.
    Combo Field::: A Widget that has both Text Field and an Drop-Down.

== View
View:: A web page that show a certain functionality, like Project View, Dashboard View.
  Dashboard View;; A View that shows dashboard.
  Form View;; A View that have multiple input widget and as for confirmation before go to next view.
    Account Merging View::: A Form View that shows account merging form.
    Copy Trans Options View:::  A Form View that shows Copy trans options.
    Login Form View::: A Form View that shows Login Form.
    Profile Editing View::: A Form View that shows profile editing form.
    Project Creating View::: A Form View that shows project creating form.
    Project Editing View:::  A Form View that shows project editing form.
    Password Changing View:: A Form View that shows password changing form.
    Registration Form View::: A Form View that shows Registration Form.
    Identity Managing View::: A Form View that shows identity managing form.
    Version Creating View::: A Form View that shows version creating form.
    Version Editing View::: A Form View that shows version creating form.

  List View;; A View that contains a List.
    Document List View::: A View that shows Document List.
    Entry List View:::
    Translation Editor View:::  A View that shows Entry List.
    Group List View::: A View that shows Group List.
    Language List View::: A View that shows Language List.
      Server Language List View::: A View that shows Server Language List.
      Project-Version Language List View::: A View that shows Project-Version Language List.
  Language Adding View;; A View for adding new language.
  Maintainer Managing View;; A View for managing maintainer.
  Profile View;; A View that shows profile of a user.
  Project View;; A View that shows project overview.
  Source Documents View;; A View for Uploading and Downloading source document.
