= Web UI Terminology
The propose of this terminology are providing a set of terms to describe user actions and components that user are likely to interact with. So we can build defect taxonomy on top of this.

== Web Generic
[glossary]
Autocomplete::
  An action on text field or text box that it predicts the complete word by typing only part of the word.

Breadcrumb::
  An widget for keeping track their locations.

Checkbox::
  A widget for binary choice.

Dialog::
  A windowed widget that prompt user for an acknowledgment. It closes after acknowledgment received. It should also close when move away from current web page.

Drop-down::
  A widget for selecting exactly one option. It expands to show a set of options when clicked; it clasped when user move focus or select an option.

Focus::
  The widget that currently receiving keyboard input.

Hyperlink::
  A UI widget that point to a web page or anchor of a web page.

List::
  An ordered group of items of same kind. E.g. Project List, Document List.

Menu::
  A collection of options or commands for user to click from.

Modal Dialog::
  A dialog that block the actions to parent web page until it close.

Pager List::
  A List that will show more items whenever user clicks "more".

Paged List::
  A List that will be split in to different pages if its length reached a given length.

Panel::
  A widget that contains other widgets and occupies an area in view. E.g. Setting Panel, Translation Memory Panel.

Password Field::
  A text field for password input.  

Radio button:
  A widget for choosing exactly on of a predefined set of options.

Search Field::
  A text field for searching.

Text Field::
  A widget for one-lined text input.

Text Box::
  A widget for multi-lined text input.

Web Page::
  A web document that can be identified with URL.

Widget::
  A UI element for viewing or interacting.

View:: 
  A web page that show a certain functionality, like Home View, Project View, Dashboard View.

== Translation
[glossary]
Chat room Panel::
  A panel that shows chat room log and text box for chat message.

Copy Source::
  Copy source strings to translation entries.

Document List::
  A Paged List that shows documents.

Document List View::
  The view that show document list.

Entry::
  A data structure that holding the relation between an source string, plural from, context, flags, comments, and translated texts. (Definition from gettext). In message list view, it represent a row. An entry may contains multiple source strings and translation strings.

Entry Row (Row)::
  A row in the message list that hold an entry. The top row is row 1 and so on. Note that a row may contain multiple source and translation entries if plural is required.

Glossary Panel::
  A panel that shows the glossary.

Keyboard shortcut dialog::
  A dialog that shows the enabled keyboard shortcut.

Notification Panel::
  A panel that displays notification.

Option Panel::
  A panel that shows configuration options.

Source Box::
  A text box that hold a source string.

Source String::
  A string to be translated. In terms of gettext, it represents msgid or msgid_plural.

State Filter::
  A set of checkboxes for filtering the translation strings by its state.

Translation Box::
  A text box that hold a translation string.

Translation Memory (TM) Panel::
  A panel that shows translation memory.

Validation Option Panel::
  A panel that shows validation options.

Translation State::
  The state of translation. It can be new, fuzzy, translated, rejected or approved.

Translation String::
  A string of translation. In terms of gettext, it represents msgstr or msgstr[n].

Translation Unit Detail::
  Data about an entry. E.g. Message Context, entry Serial number, and REST id.

== Dashboard
Activity List::
  A Pager List for activities.

Maintained Project List::
  A Pager List for user maintained projects.

== Projects
Copy Trans Options View::
  A View for configure copy trans options.

Maintainer Managing View::
  A View for managing maintainer.

Project List::
  A Paged List for projects.

Project Creating View::
  A View for creating project.

Project Editing View::
  A view for editing project.

Project Search Field::
  A search field for searching projects.

Source Documents View::
  A View for Uploading and Downloading source document.

Version List::
  A Paged List for versions.

Version Creating View::
  A View for creating version.

Version Editing View::
  A View for editing version.

== Languages


== Group
== Glossary
== Administration Menus 
== Setting
== Login
== Register

